import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

import HeaderTop from "@/components/headerTop/HeaderTop";
import HeaderMain from "@/components/headerMain/HeaderMain";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const poppinsFont = Poppins({
//   variable: "--font-poppins-serif",
//   subsets: ["latin"],
//   weight: ["500", "700"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <HeaderTop /> */}
        <HeaderMain />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
