export interface Product {
  id: number;
  title: string;
  description: string;
  waist: string;
  image: string;
  price: number;
  category: string;
}

export const worksData: Product[] = [
  {
    id: 1,
    title: "Chaleco granix",
    description: "Lana LHO",
    waist: "1, 2 y 3",
    price: 145.000,
    image: "/images/works/work1/chaleco-granix1.jpg",
    category: "Mujer",
  },
  {
    id: 2,
    title: "Cardigan pancito",
    description: "Lana cisne Semi gorda",
    waist: "2 super ancho",
    price: 212.000,
    image: "/images/works/work2/cardigan-pancito1.jpg",
    category: "Mujer",
  },
  {
    id: 3,
    title: "Sueter combinado",
    description: "Lana 2/2",
    waist: "1, 2, 3",
    price: 189.000,
    image: "/images/works/work3/sueter-combinado1.jpg",
    category: "Mujer",
  },
  {
    id: 4,
    title: "Chaleco trenza",
    description: "Lana idlio LHO",
    waist: "1, 2, 3",
    price: 189.000,
    image: "/images/works/work4/chaleco-trenza1.jpg",
    category: "Mujer",
  },
  {
    id: 5,
    title: "Bufanda granix",
    description: "Lana idlio LHO",
    waist: "",
    price: 106.000,
    image: "/images/works/work5/bufanda-granix1.jpg",
    category: "Mujer",
  },
  {
    id: 6,
    title: "Sueter 3/4",
    description: "Lana 2/2",
    waist: "",
    price: 189.000,
    image: "/images/works/work6/sueter1.jpg",
    category: "Mujer",
  },
  {
    id: 7,
    title: "Gorro capucha",
    description: "Lana cashmilon",
    waist: "",
    price: 78.000,
    image: "/images/works/work7/gorro-capucha1.jpg",
    category: "Mujer",
  },
  {
    id: 8,
    title: "Chalec jersey",
    description: "Hilo de algodón",
    waist: "",
    price: 134.000,
    image: "/images/works/work8/chaleco1.jpg",
    category: "Mujer",
  },
  {
    id: 9,
    title: "Sueter red",
    description: "Hilo de algodón",
    waist: "",
    price: 167.000,
    image: "/images/works/work9/sueter1.jpg",
    category: "Mujer",
  },
  {
    id: 10,
    title: "Pollera red",
    description: "Hilo de algodón",
    waist: "",
    price: 145.000,
    image: "/images/works/work10/poyera1.jpg",
    category: "Mujer",
  },
  {
    id: 11,
    title: "Vestido Vicky",
    description: "Hilo de algodón",
    waist: "",
    price: 245.000,
    image: "/images/works/work11/vestido1.jpg",
    category: "Mujer",
  },
  {
    id: 12,
    title: "Gorro",
    description: "Lana",
    waist: "",
    price: 100,
    image: "/images/works/work12/gorro1.jpg",
    category: "Mujer",
  },
  {
    id: 13,
    title: "Gorro",
    description: "Hilo de algodón",
    waist: "",
    price: 34.000,
    image: "/images/works/work13/gorro1.jpg",
    category: "Mujer",
  },
  {
    id: 14,
    title: "Cartera",
    description: "Lana",
    waist: "",
    price: 100,
    image: "/images/works/work14/cartera1.jpg",
    category: "Mujer",
  },
  {
    id: 15,
    title: "Cartera",
    description: "Lana",
    waist: "",
    price: 100,
    image: "/images/works/work15/cartera1.jpg",
    category: "Mujer",
  },
  {
    id: 16,
    title: "Chaleco",
    description: "Lana",
    waist: "",
    price: 100,
    image: "/images/works/work16/chaleco1.jpg",
    category: "Mujer",
  },
  {
    id: 17,
    title: "Remera candia",
    description: "Hilo de algodón",
    waist: "",
    price: 134.000,
    image: "/images/works/work17/chaleco1.jpg",
    category: "Mujer",
  },
  {
    id: 18,
    title: "Mini sueter jazmín",
    description: "Hilo Fidelio",
    waist: "",
    price: 123.000,
    image: "/images/works/work18/remera1.jpg",
    category: "Mujer",
  },
  {
    id: 19,
    title: "Gorro",
    description: "Hilo de algodón",
    waist: "",
    price: 39.000,
    image: "/images/works/work19/gorro1.jpg",
    category: "Mujer",
  },
  {
    id: 20,
    title: "Remera",
    description: "Hilo de algodón",
    waist: "",
    price: 134.000,
    image: "/images/works/work20/chaleco1.jpg",
    category: "Mujer",
  },
  {
    id: 21,
    title: "Sueter",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work21/sueter1.jpg",
    category: "Mujer",
  },
  {
    id: 22,
    title: "Sueter",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work22/sueter1.jpg",
    category: "Mujer",
  },
  {
    id: 23,
    title: "Sueter",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work23/sueter1.jpg",
    category: "Mujer",
  },
  {
    id: 24,
    title: "Gorro",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work24/gorro1.jpg",
    category: "Mujer",
  },
  {
    id: 25,
    title: "Gorro",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work25/gorro2.jpg",
    category: "Mujer",
  },
  {
    id: 26,
    title: "Bolso",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work26/bolso2.jpg",
    category: "Mujer",
  },
  {
    id: 27,
    title: "Cuello",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work27/cuello2.jpg",
    category: "Mujer",
  },
  {
    id: 28,
    title: "Pantalon",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work28/pantalon4.jpg",
    category: "Mujer",
  },
  {
    id: 29,
    title: "Oso",
    description: "Amigurumi",
    waist: "",
    price: 0.000,
    image: "/images/works/work29/oso1.jpg",
    category: "Niño",
  },
  {
    id: 30,
    title: "Oso",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work30/Oso7.jpg",
    category: "Niño",
  },
  {
    id: 31,
    title: "Body",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work31/IMG-20250308-WA0034.jpg",
    category: "Bebé",
  },
  {
    id: 32,
    title: "Gorro",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work32/IMG-20250308-WA0040.jpg",
    category: "Bebé",
  },
  {
    id: 33,
    title: "Gorro",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work33/IMG-20250308-WA0044.jpg",
    category: "Bebé",
  },
  {
    id: 34,
    title: "Chaleco",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work34/IMG-20250308-WA0047.jpg",
    category: "Bebé",
  },
  {
    id: 35,
    title: "Chaleco",
    description: "Amigurumi",
    waist: "",
    price: 0.000,
    image: "/images/works/work35/IMG-20250308-WA0048.jpg",
    category: "Bebé",
  },
  {
    id: 36,
    title: "Campera",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work36/IMG-20250308-WA0051.jpg",
    category: "Bebé",
  },
  {
    id: 37,
    title: "Body",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work37/IMG-20250308-WA0052.jpg",
    category: "Bebé",
  },
  {
    id: 38,
    title: "Body",
    description: "Amigurumi",
    waist: "",
    price: 0.000,
    image: "/images/works/work38/IMG-20250308-WA0053.jpg",
    category: "Bebé",
  },
  {
    id: 39,
    title: "Campera",
    description: "Lana",
    waist: "",
    price: 0.000,
    image: "/images/works/work39/IMG-20250308-WA0062.jpg",
    category: "Bebé",
  },
]